apiVersion: v1
kind: Service
metadata:
  name: agry-api-gateway-service
  namespace: default
  labels:
    app: agry-api-gateway
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: agry-api-gateway
